# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa57307bce5e415ca8b8d74e1d3ca975dc7e64188d41ae18a6285f13871ed8e414ff418d9000f6bd05bae4d48ac7486b3cb7872ef3081856bbd7c1ca7980d83

test:
  secret_key_base: 4c1b9ddd446ce96d72ee9082224cf1aa69136f03843ffbbb09c6481d37c26def46c2f0936abcc42889f32c36e1368f9d31b2c1c1c2787e0248d26fcfc60a5c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
